keybinding:
  universal:
    prevItem-alt: 'e' # go one line up
    nextItem-alt: 'n' # go one line down
    nextMatch: 'k'
    prevMatch: 'K'
    new: 'k'
    edit: '!'
    scrollUpMain-alt1: 'E' # main panel scroll up
    scrollDownMain-alt1: 'N' # main panel scroll down
    moveDownCommit: '<c-n>' # move commit down one
    moveUpCommit: '<c-e>' # move commit up one
gui:
  theme:
    activeBorderColor:
      - '#a6e3a1'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#a6e3a1'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

  authorColors:
    '*': '#b4befe'
git:
  log:
    order: default
