[mgr]
prepend_keymap = [
	{ on = "n", run = "arrow 1", desc = "Move cursor down"},
	{ on = "e", run = "arrow -1", desc = "Move cursor up"},

	{ on = "N", run = "seek 5",  desc = "Seek down 5 units in the preview" },
	{ on = "E", run = "seek -5", desc = "Seek up 5 units in the preview" },

	{ on = "j", run = "forward --end-of-word", desc = "Move forward to the end of the current or next word"},
	{ on = "J", run = "forward --far --end-of-word", desc = "Move forward to the end of the current or next WORD"},
	{ on = "k", run = "find_arrow", desc = "Goto the next found" },
	{ on = "K", run = "find_arrow --previous", desc = "Goto the previous found" },
]

[tasks]
prepend_keymap = [
	{ on = "n", run = "arrow 1", desc = "Move cursor down"},
	{ on = "e", run = "arrow -1", desc = "Move cursor up"},
]

[spot]
prepend_keymap = [
	{ on = "n", run = "arrow 1", desc = "Move cursor down"},
	{ on = "e", run = "arrow -1", desc = "Move cursor up"},
]

[pick]
prepend_keymap = [
	{ on = "n", run = "arrow 1", desc = "Move cursor down"},
	{ on = "e", run = "arrow -1", desc = "Move cursor up"},
	{ on = "k", run = "close", desc = "Cancel the confirm" },
]


[confirm]
prepend_keymap = [
	{ on = "n", run = "arrow 1", desc = "Move cursor down"},
	{ on = "e", run = "arrow -1", desc = "Move cursor up"},
]

[help]
prepend_keymap = [
	{ on = "n", run = "arrow 1", desc = "Move cursor down"},
	{ on = "e", run = "arrow -1", desc = "Move cursor up"},
]
