[opener]
edit = [
	{ run = "nvim %*",  block = true, desc = "nvim", for = "windows" },
	{ run = "nvim $@",  block = true, desc = "nvim", for = "unix" },
]

[mgr]
ratio = [2,4,4]
show_hidden = true
show_symlink = true
linemode = "size"

